routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    //return view('welcome');
    return view('utama.main');
});*/

Route::get('/test', function () {
    
    return view('adminpage.message.template_reply');
});

Route::get('/', 'Utama\UtamaController@index');
Route::post('praaplication/store', 'Praaplication\PraaplicationController@store');
Route::get('praapplication/{id}', 'Praaplication\PraaplicationController@kira');




Route::resource('cif', 'CifController');

Route::get('/hidden', 'Utama\UtamaController@hidden');

Route::get('about', 'Utama\UtamaController@about');
Route::get('service', 'Utama\UtamaController@service');
Route::get('faq', 'Utama\UtamaController@faq');
Route::get('contact', 'Utama\UtamaController@contact');
//Route::post('/praaplication/save', 'Praaplication\PraaplicationController@save_praaplication');

Route::resource('message', 'Utama\MessageController');
Route::get('/reply-que/{id}', 'Utama\MessageController@show');
Route::post('/reply_post', 'Utama\MessageController@update');

Route::resource('praaplication', 'Praaplication\PraaplicationController');

Route::post('/praaplication/kelayakan', 'Praaplication\PraaplicationController@kelayakan');
Route::get('/praaplication/upload-file/{id}', 'Praaplication\PraaplicationController@upload');
Route::post('/praaplication/upload-file/uploads/{id}', 'Praaplication\PraaplicationController@uploads');
Route::post('/praaplication/finish', 'Praaplication\PraaplicationController@finish');
Route::get('upload-praaplication', 'Praaplication\PraaplicationController@upload');

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/adminnew', 'AdminNewController@index')->name('adminnew');


Route::group( ['middleware' => ['auth']], function() {
    Route::resource('mo', 'MOController');
    Route::get('/add_leader/{id}', 'MOController@add_leader');
    Route::post('/mo/add_leader', 'MOController@post_leader'); 
    Route::get('/mo/update1/{id}', 'MOController@updatestatus1'); 
    Route::get('/mo/update2/{id}', 'MOController@updatestatus2');
    Route::get('/add_manager/{id}', 'MOController@add_manager');
    Route::post('/mo/add_manager', 'MOController@post_manager'); 
    

    Route::resource('users', 'UserController');
    Route::get('/users/edit/{id}', 'UserController@edit');
    Route::delete('/users/destroy/{id}', 'UserController@destroy');
    Route::resource('stage', 'StageController');
    Route::resource('profile1', 'ProfileController');
    Route::post('/save/profile/{id}', 'ProfileController@store_profile');
    Route::post('/save/background/{id}', 'ProfileController@store_background');
    Route::resource('cus_mo', 'CustomerMoController');
    
    Route::post('/profileupdate', 'ProfileController@update');
    

    Route::get('/userdata/update/{id}', 'UserController@updatestatus'); 
    Route::get('/userdata/update1/{id}', 'UserController@updatestatus1'); 
    Route::post('/users/status/{id}', 'UserController@status'); //tes
    
    Route::resource('roles', 'RoleController');
    Route::resource('loan', 'LoanController');
    
    Route::get('/location/show/{id}', 'AdminNewController@view_location');
    Route::get('/history/show/{id}', 'AdminNewController@view_history');
    Route::get('/doc/show/{cus_id}', 'AdminNewController@view_doc');
    Route::get('/doc/submit/{id}', 'AdminNewController@submit_doc_cus');
    Route::post('/doc/submit/uploads/{id}', 'AdminNewController@uploads');

    //Processor 1
    Route::get('/assess_addcus', 'AssessmentController@create');
    Route::get('/doc/spekar/{id}', 'AdminNewController@submit_verify');
    Route::get('/speakar/doc/{id}', 'AssessmentController@kira');
    Route::post('/oassessment/kira/uploads/{id}', 'AssessmentController@uploads');
    Route::post('/save/spekar/{id}', 'LoanEliController@store');
    Route::get('/doc/spekardown/{cus_id}', 'LoanEliController@show');
    Route::post('/routeto/user/{id}', 'LoanEliController@routeto');
    Route::post('/send_spekar', 'LoanEliController@spekar_routeto');
    Route::get('/uploadspekar_p1', 'POneController@uploadspekar_p1');
    Route::get('/route_to_mo', 'POneController@route_to_mo');
    Route::post('/iclocreject/{id}', 'POneController@iclocreject');

    

    //Processor 2 
    Route::get('/loan_internal/calculation/{id}', 'PSecondController@loan_internal_cal_perone');
    //Route::post('/save/process6/{id}', 'LoanEliController@process6'); //hidden hitungan dsr
    Route::post('/save/process6/{id}', 'PSecondController@post_loan_cal_p2');
    Route::get('/pdfbatchheader/{id}', 'LoanEliController@pdfbatchheader');
    Route::get('/processor2/loancal/{id}', 'PSecondController@loan_cal');
    Route::post('/p2/custtenus/result', 'PSecondController@post_tenus_p2');
    Route::get('/processor2/recount/{id}', 'PSecondController@loan_cal');
    Route::get('/processor2/{id}/step1', 'PSecondController@step1');
    //Route::post('/tenos/custtenus/store', 'LoanEliController@post_tenus_step1');
    //Route::post('/tenos/custtenus/store_step1', 'PSecondController@post_tenus_step1');
    
    
    
    
    //PRocess 3 
    Route::post('/save/process7/{id}', 'LoanEliController@process7');
    Route::post('/save/process8/{id}', 'LoanEliController@process8');

    //Processor 4
    Route::get('/loan-eli/process11', 'LoanEliController@process11');
    Route::get('/report_monthly', 'ReportManagerController@report_processor4');
    Route::get('/appdisbursement/{id}', 'LoanEliController@disbursement');
    Route::get('/rejectdisbursement/{id}', 'LoanEliController@rejectdisbursement');
    Route::post('/adddocprocess11/{id}', 'LoanEliController@adddocprocess11');
    
    
    //MO  
    Route::resource('/mo_cal', 'PMOController');
    Route::get('/mo_cal_check', 'PMOController@mo_cal_check');
    Route::get('/loan/eli/scoring/{id}', 'PMOController@mo_cal_check_perone');
    Route::get('/cal/change/{id}', 'PMOController@cal_change');
    Route::get('/doc/incomplete/{id}', 'PMOController@doc_incomplete');
    Route::get('/doc/additional/{id}', 'PMOController@doc_additional');
    Route::get('/pendingdoc', 'PMOController@pending_doc');
    Route::get('/pendingdoc/perone/{id}', 'PMOController@pendingdoc_perone');
    Route::get('/doc/icloc/{id}', 'PMOController@doc_iclocreject');    
    //Route::get('/doc/icloc/{id}', 'AssessmentController@kira');
    //Route::get('/assessment/kira/{id}', 'AssessmentController@kira');
    Route::get('/ic_loc_update/{id}', 'PMOController@update_locic');
    Route::post('/passreject/mo/{id}', 'PMOController@passreject_mo');
    
    //Route::post('/passreject/mo/{id}', 'LoanEliController@passreject_mo');
    Route::post('/download/spekar/{id}', 'LoanEliController@download_spekar');
    Route::post('/save/meetcus/{id}', 'LoanEliController@meetcus');
    Route::get('/tenos/custtenos/{id}', 'LoanEliController@kelayakantenos');
    
    Route::get('/upload_ic_loc_back/{id}', 'LoanEliController@upload_ic_loc_back');
    
    Route::post('/save_tenure', 'LoanEliController@save_tenure');
    Route::get('/resulttenus/{id}', 'LoanEliController@resulttenus');
    Route::post('/tenos/custtenus/store', 'LoanEliController@post_tenus_step1');
    Route::resource('/docincomplete', 'DocumentIncompleteController');
    Route::get('/nextcalchange', 'DocumentIncompleteController@nextcalchange');
    Route::get('/locic/rejectic_loc', 'DocumentIncompleteController@reject_ic_loc');

    //moaqs
    Route::resource('/moaqs', 'MoaqsController');
    Route::get('/moaqs/test', 'MoaqsController@show');
    
    

    //test verifikasi
    Route::get('/verifikasi/{id}', 'AdminNewController@ver');

    //Veryfy MO 1
    Route::post('/verifymo', 'AssessmentController@ver_mo');    
    
    Route::resource('/assess', 'AssessmentController');
    Route::resource('assessment', 'AssessmentController');
    Route::resource('assessment1', 'AssessmentController');
    Route::get('/assessment/kira/{id}', 'AssessmentController@kira');
    
    Route::post('/assessment/kira/uploads/{id}', 'AssessmentController@uploads');
    Route::get('/send/mbsb', 'AssessmentController@send_mbsb');
    Route::post('/send/mbsbdata', 'AssessmentController@post_send_mbsb');
    Route::get('/stage/update/{id}', 'AssessmentController@stage_update');

    //Send n attacth to gmail
    Route::get('/send/excel', 'AssessmentController@send_excel');
    Route::post('/send/excel', 'AssessmentController@send_excel');
    Route::post('/send_to_generate', 'AssessmentController@save_table');
    Route::post('/send_aset', 'AssessmentController@save_table');

    //Report Manager
    Route::resource('report-manager', 'ReportManagerController');
    Route::get('/make-new-cus/{id}', 'ReportManagerController@make_new_cus');
    

    Route::resource('posts', 'PostController');
    Route::resource('comments', 'CommentController');
    
    Route::resource('homeimage', 'Utama\HomeImageController');
    Route::get('testUrl/{id}', 'Utama\HomeImageController@edit');
    Route::get('/homeimage/update1/{id}', 'Utama\HomeImageController@update1');
    Route::get('/homeimage/update2/{id}', 'Utama\HomeImageController@update2');

    /*Setup Module*/
    Route::resource('package', 'PackageController');
    Route::resource('employment', 'EmploymentController');
    Route::resource('employment', 'EmploymentController');
    Route::resource('rate', 'RateController');
    Route::resource('loanpkg', 'LoanpkgController');
    Route::get('/loanpackage/update/{id}', 'LoanpkgController@act');
    Route::get('/loanpackage/update1/{id}', 'LoanpkgController@act1');
    Route::resource('comm', 'CommController');

resources/views/adminpage/setupmodule/jenispekerjaan/edit.blade.php
@extends('vadmin.tampilan')

@section('content')

	<section class="content">
        <div class="container-fluid">
            
            <div class="row clearfix"> <!-- Breadcrumber -->
                <div class="col-md-6">
                    <ol class="breadcrumb breadcrumb-col-pink">
                        <li><a href="javascript:void(0);"><i class="material-icons">text_fields</i> Setup Module</a></li>
                        <li><a href="{{route('employment.index')}}"><i class="material-icons">next_week</i> Job Type</a></li>
                        @if(Request::segment(2) === 'create')
                        <li class="active"><i class="material-icons">create</i>Add</li>
                        @else
                        <li class="active"><i class="material-icons">edit</i> Edit</li>
                        @endif
                    </ol>
                </div>
            </div> <!-- End of breadcrumber -->

            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header bg-red">
                            <h2>Edit</h2>
                        </div>

                        <div class="body">
                            <div class="row clearfix">
                                {!! Form::model($employment, ['method' => 'PUT', 'route' => ['employment.update',  $employment->id ] ]) !!}
                                    
                                    @include('adminpage.setupmodule.jenispekerjaan.form')
                                    
                                    <div class="col-xs-6 col-sm-3 col-md-2 col-lg-2 col-md-offset-10">
                                        <button type="submit" class="btn bg-green btn-block btn-lg waves-effect">
                                            Save
                                        </button>
                                        {{ csrf_field() }}
                                    </div>
                                    
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>

        </div>
    </section>

@endsection

resources/views/adminpage/setupmodule/jenispekerjaan/form.blade.php
<div class="col-sm-12">
    <h5>Job Type Code:</h5>
    <div class="form-group form-float @if ($errors->has('code_employment')) has-error @endif">
        <div class="form-line">            
            {!! Form::label('title', 'Job Type Code', ['class' => 'form-label']) !!}
            {!! Form::text('code_employment', null, ['class' => 'form-control']) !!}
            @if ($errors->has('code_employment')) <p class="help-block">{{ $errors->first('code_employment') }}</p> @endif            
            <div class="help-info">Max 4 char</div>
        </div>
    </div>
</div>


<div class="col-sm-12">
    <h5>Job Type:</h5>
    <div class="form-group form-float @if ($errors->has('name')) has-error @endif">
        <div class="form-line">            
            {!! Form::label('title', 'Job Type', ['class' => 'form-label']) !!}
            {!! Form::text('name', null, ['class' => 'form-control']) !!}
            @if ($errors->has('name')) <p class="help-block">{{ $errors->first('name') }}</p> @endif            
        </div>
    </div>
</div>

resources/views/adminpage/setupmodule/jenispekerjaan/index.blade.php
@extends('vadmin.tampilan')

@section('content')

	<section class="content">
        <div class="container-fluid">
            
            <div class="row clearfix"> <!-- Breadcrumber -->
                <div class="col-md-6">
                    <ol class="breadcrumb breadcrumb-col-pink">
                        <li><a href="javascript:void(0);"><i class="material-icons">text_fields</i> Attribute</a></li>
                        <li class="active"><i class="material-icons">next_week</i> Job Type</li>
                        
                    </ol>
                </div>
            </div> <!-- End of breadcrumber -->

            <!-- Notification -->
            <div class="row clearfix">
                @if ($message = Session::get('success')) 
                <div class="alert bg-green alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ $message }}
                </div>
                @elseif($message = Session::get('delete'))
                <div class="alert bg-pink alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ $message }}
                </div>
                @elseif($message = Session::get('update'))
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ $message }}
                </div>
                @endif
            </div>
            <!-- End of Notif -->

            <div class="row clearfix demo-button-sizes"><!-- Button tambah -->
                <div class="col-md-10"></div>
                
                <div class="col-xs-6 col-sm-3 col-md-2 col-lg-2">
                    <a href="{{ route('employment.create') }}" type="submit" class="btn btn-success btn-block btn-lg waves-effect" style="cursor:pointer;">
                      Add
                    </a>
                </div>
                
            </div> <!-- End of button tambah -->

            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header bg-red">
                            Job Type
                        </div>
                        <div class="body">
                            <table class="table" id="data-table">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Job Type Code</th>
                                        <th>Job Type</th>
                                        <th width="20%">Action</th>            
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php $i = 1; ?>

                                    @foreach($employment as $data)
                                    <tr>
                                        <td>{{$i++}}</td>
                                        <td>{{$data -> code_employment}}</td>
                                        <td>{{$data -> name}}</td>
                                        <td>
                                            @include('shared._actions', [
					                            'entity' => 'employment',
					                            'id' => $data->id
					                        ])
                                         </td>
                                    </tr>
                                    @endforeach

        
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.flash.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js"></script>

    <script>
        $(document).ready(function() {
        $('#data-table').DataTable();
        });
    </script>

@endsection

resources/views/adminpage/setupmodule/jenispekerjaan/new.blade.php
@extends('vadmin.tampilan')

@section('content')

	<section class="content">
        <div class="container-fluid">
            
            <div class="row clearfix"> <!-- Breadcrumber -->
                <div class="col-md-6">
                    <ol class="breadcrumb breadcrumb-col-pink">
                        <li><a href="javascript:void(0);"><i class="material-icons">text_fields</i> Setup Module</a></li>
                        <li><a href="{{route('employment.index')}}"><i class="material-icons">next_week</i> Job Type</a></li>
                        @if(Request::segment(2) === 'create')
                        <li class="active"><i class="material-icons">create</i>Add</li>
                        @else
                        <li class="active"><i class="material-icons">edit</i> Edit</li>
                        @endif
                    </ol>
                </div>
            </div> <!-- End of breadcrumber -->

            <div class="row clearfix">
                <div class="col-md-12">
                    <div class="card">
                        <div class="header bg-red">
                            <h2>Add</h2>
                        </div>

                        <div class="body">
                            <div class="row clearfix">
                                {!! Form::open(['route' => ['employment.store'] ]) !!}
                                    @include('adminpage.setupmodule.jenispekerjaan.form')
                                    
                                    <div class="col-xs-6 col-sm-3 col-md-2 col-lg-2 col-md-offset-10">
                                        <button type="submit" class="btn bg-green btn-block btn-lg waves-effect">
                                            Save
                                        </button>
                                        {{ csrf_field() }}
                                    </div>
                                    
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>

        </div>
    </section>

@endsection