routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    //return view('welcome');
    return view('utama.main');
});*/

Route::get('/test', function () {
    
    return view('adminpage.message.template_reply');
});

Route::get('/', 'Utama\UtamaController@index');
Route::post('praaplication/store', 'Praaplication\PraaplicationController@store');
Route::get('praapplication/{id}', 'Praaplication\PraaplicationController@kira');




Route::resource('cif', 'CifController');

Route::get('/hidden', 'Utama\UtamaController@hidden');

Route::get('about', 'Utama\UtamaController@about');
Route::get('service', 'Utama\UtamaController@service');
Route::get('faq', 'Utama\UtamaController@faq');
Route::get('contact', 'Utama\UtamaController@contact');
//Route::post('/praaplication/save', 'Praaplication\PraaplicationController@save_praaplication');

Route::resource('message', 'Utama\MessageController');
Route::get('/reply-que/{id}', 'Utama\MessageController@show');
Route::post('/reply_post', 'Utama\MessageController@update');

Route::resource('praaplication', 'Praaplication\PraaplicationController');

Route::post('/praaplication/kelayakan', 'Praaplication\PraaplicationController@kelayakan');
Route::get('/praaplication/upload-file/{id}', 'Praaplication\PraaplicationController@upload');
Route::post('/praaplication/upload-file/uploads/{id}', 'Praaplication\PraaplicationController@uploads');
Route::post('/praaplication/finish', 'Praaplication\PraaplicationController@finish');
Route::get('upload-praaplication', 'Praaplication\PraaplicationController@upload');

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::get('/adminnew', 'AdminNewController@index')->name('adminnew');


Route::group( ['middleware' => ['auth']], function() {
    Route::resource('mo', 'MOController');
    Route::get('/add_leader/{id}', 'MOController@add_leader');
    Route::post('/mo/add_leader', 'MOController@post_leader'); 
    Route::get('/mo/update1/{id}', 'MOController@updatestatus1'); 
    Route::get('/mo/update2/{id}', 'MOController@updatestatus2');
    Route::get('/add_manager/{id}', 'MOController@add_manager');
    Route::post('/mo/add_manager', 'MOController@post_manager'); 
    

    Route::resource('users', 'UserController');
    Route::get('/users/edit/{id}', 'UserController@edit');
    Route::delete('/users/destroy/{id}', 'UserController@destroy');
    Route::resource('stage', 'StageController');
    Route::resource('profile1', 'ProfileController');
    Route::post('/save/profile/{id}', 'ProfileController@store_profile');
    Route::post('/save/background/{id}', 'ProfileController@store_background');
    Route::resource('cus_mo', 'CustomerMoController');
    
    Route::post('/profileupdate', 'ProfileController@update');
    

    Route::get('/userdata/update/{id}', 'UserController@updatestatus'); 
    Route::get('/userdata/update1/{id}', 'UserController@updatestatus1'); 
    Route::post('/users/status/{id}', 'UserController@status'); //tes
    
    Route::resource('roles', 'RoleController');
    Route::resource('loan', 'LoanController');
    
    Route::get('/location/show/{id}', 'AdminNewController@view_location');
    Route::get('/history/show/{id}', 'AdminNewController@view_history');
    Route::get('/doc/show/{cus_id}', 'AdminNewController@view_doc');
    Route::get('/doc/submit/{id}', 'AdminNewController@submit_doc_cus');
    Route::post('/doc/submit/uploads/{id}', 'AdminNewController@uploads');

    //Processor 1
    Route::get('/assess_addcus', 'AssessmentController@create');
    Route::get('/doc/spekar/{id}', 'AdminNewController@submit_verify');
    Route::get('/speakar/doc/{id}', 'AssessmentController@kira');
    Route::post('/oassessment/kira/uploads/{id}', 'AssessmentController@uploads');
    Route::post('/save/spekar/{id}', 'LoanEliController@store');
    Route::get('/doc/spekardown/{cus_id}', 'LoanEliController@show');
    Route::post('/routeto/user/{id}', 'LoanEliController@routeto');
    Route::post('/send_spekar', 'LoanEliController@spekar_routeto');
    Route::get('/uploadspekar_p1', 'POneController@uploadspekar_p1');
    Route::get('/route_to_mo', 'POneController@route_to_mo');
    Route::post('/iclocreject/{id}', 'POneController@iclocreject');

    

    //Processor 2 
    Route::get('/loan_internal/calculation/{id}', 'PSecondController@loan_internal_cal_perone');
    //Route::post('/save/process6/{id}', 'LoanEliController@process6'); //hidden hitungan dsr
    Route::post('/save/process6/{id}', 'PSecondController@post_loan_cal_p2');
    Route::get('/pdfbatchheader/{id}', 'LoanEliController@pdfbatchheader');
    Route::get('/processor2/loancal/{id}', 'PSecondController@loan_cal');
    Route::post('/p2/custtenus/result', 'PSecondController@post_tenus_p2');
    Route::get('/processor2/recount/{id}', 'PSecondController@loan_cal');
    Route::get('/processor2/{id}/step1', 'PSecondController@step1');
    //Route::post('/tenos/custtenus/store', 'LoanEliController@post_tenus_step1');
    //Route::post('/tenos/custtenus/store_step1', 'PSecondController@post_tenus_step1');
    
    
    
    
    //PRocess 3 
    Route::post('/save/process7/{id}', 'LoanEliController@process7');
    Route::post('/save/process8/{id}', 'LoanEliController@process8');

    //Processor 4
    Route::get('/loan-eli/process11', 'LoanEliController@process11');
    Route::get('/report_monthly', 'ReportManagerController@report_processor4');
    Route::get('/appdisbursement/{id}', 'LoanEliController@disbursement');
    Route::get('/rejectdisbursement/{id}', 'LoanEliController@rejectdisbursement');
    Route::post('/adddocprocess11/{id}', 'LoanEliController@adddocprocess11');
    
    
    //MO  
    Route::resource('/mo_cal', 'PMOController');
    Route::get('/mo_cal_check', 'PMOController@mo_cal_check');
    Route::get('/loan/eli/scoring/{id}', 'PMOController@mo_cal_check_perone');
    Route::get('/cal/change/{id}', 'PMOController@cal_change');
    Route::get('/doc/incomplete/{id}', 'PMOController@doc_incomplete');
    Route::get('/doc/additional/{id}', 'PMOController@doc_additional');
    Route::get('/pendingdoc', 'PMOController@pending_doc');
    Route::get('/pendingdoc/perone/{id}', 'PMOController@pendingdoc_perone');
    Route::get('/doc/icloc/{id}', 'PMOController@doc_iclocreject');    
    //Route::get('/doc/icloc/{id}', 'AssessmentController@kira');
    //Route::get('/assessment/kira/{id}', 'AssessmentController@kira');
    Route::get('/ic_loc_update/{id}', 'PMOController@update_locic');
    Route::post('/passreject/mo/{id}', 'PMOController@passreject_mo');
    
    //Route::post('/passreject/mo/{id}', 'LoanEliController@passreject_mo');
    Route::post('/download/spekar/{id}', 'LoanEliController@download_spekar');
    Route::post('/save/meetcus/{id}', 'LoanEliController@meetcus');
    Route::get('/tenos/custtenos/{id}', 'LoanEliController@kelayakantenos');
    
    Route::get('/upload_ic_loc_back/{id}', 'LoanEliController@upload_ic_loc_back');
    
    Route::post('/save_tenure', 'LoanEliController@save_tenure');
    Route::get('/resulttenus/{id}', 'LoanEliController@resulttenus');
    Route::post('/tenos/custtenus/store', 'LoanEliController@post_tenus_step1');
    Route::resource('/docincomplete', 'DocumentIncompleteController');
    Route::get('/nextcalchange', 'DocumentIncompleteController@nextcalchange');
    Route::get('/locic/rejectic_loc', 'DocumentIncompleteController@reject_ic_loc');

    //moaqs
    Route::resource('/moaqs', 'MoaqsController');
    Route::get('/moaqs/test', 'MoaqsController@show');
    
    

    //test verifikasi
    Route::get('/verifikasi/{id}', 'AdminNewController@ver');

    //Veryfy MO 1
    Route::post('/verifymo', 'AssessmentController@ver_mo');    
    
    Route::resource('/assess', 'AssessmentController');
    Route::resource('assessment', 'AssessmentController');
    Route::resource('assessment1', 'AssessmentController');
    Route::get('/assessment/kira/{id}', 'AssessmentController@kira');
    
    Route::post('/assessment/kira/uploads/{id}', 'AssessmentController@uploads');
    Route::get('/send/mbsb', 'AssessmentController@send_mbsb');
    Route::post('/send/mbsbdata', 'AssessmentController@post_send_mbsb');
    Route::get('/stage/update/{id}', 'AssessmentController@stage_update');

    //Send n attacth to gmail
    Route::get('/send/excel', 'AssessmentController@send_excel');
    Route::post('/send/excel', 'AssessmentController@send_excel');
    Route::post('/send_to_generate', 'AssessmentController@save_table');
    Route::post('/send_aset', 'AssessmentController@save_table');

    //Report Manager
    Route::resource('report-manager', 'ReportManagerController');
    Route::get('/make-new-cus/{id}', 'ReportManagerController@make_new_cus');
    

    Route::resource('posts', 'PostController');
    Route::resource('comments', 'CommentController');
    
    Route::resource('homeimage', 'Utama\HomeImageController');
    Route::get('testUrl/{id}', 'Utama\HomeImageController@edit');
    Route::get('/homeimage/update1/{id}', 'Utama\HomeImageController@update1');
    Route::get('/homeimage/update2/{id}', 'Utama\HomeImageController@update2');

    /*Setup Module*/
    Route::resource('package', 'PackageController');
    Route::resource('employment', 'EmploymentController');
    Route::resource('employment', 'EmploymentController');
    Route::resource('rate', 'RateController');
    Route::resource('loanpkg', 'LoanpkgController');
    Route::get('/loanpackage/update/{id}', 'LoanpkgController@act');
    Route::get('/loanpackage/update1/{id}', 'LoanpkgController@act1');
    Route::resource('comm', 'CommController');

app/Http/Controllers/MOController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Role;
use App\LeaderMO;
use App\Manager;
use App\Permission;
use App\Authorizable;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use DB;
use App\Model_has_role;
class MOController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = DB::table('users')
                    ->join('model_has_roles', 'model_has_roles.model_id', '=', 'users.id')
                    ->join('roles', 'roles.id', '=', 'model_has_roles.role_id')
                    ->where('model_has_roles.role_id',  3)
                    ->select('users.id AS id', 'users.name AS name', 'users.email AS email', 'users.status AS status', 'users.status_head AS status_head', 'users.leader AS leader', 'users.manager AS manager','users.name_manager AS name_manager')
                    ->paginate();

         $name_manager = User::get();

         $result = User::get();          
                    
        return view('adminpage.user.mo.index', compact('result','name_manager'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::where('id','=', '3')->pluck('name', 'id');

        return view('adminpage.user.mo.new', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'bail|required|min:2',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6',
            'roles' => 'required|min:1',
            'leader' => 'nullable|min:1',
            'status_head' => 'nullable'
        ]);

        $request->merge(['password' => bcrypt($request->get('password'))]);

        // Create the user
        if ( $user = User::create($request->except('roles', 'permissions')) ) {

            $this->syncPermissions($request, $user);

            flash('User has been created.');

        } else {
            flash()->error('Unable to create user.');
        }


        //cek apakah input head 1 atau 0  belum bisa guna
        /*if($request->input('head') == 1){
            $name = $request->input('name');

            $doc               = new LeaderMO;
            $doc->leader_name  = $name;
            
            $doc->save();

        }*/

        return redirect()->route('mo.index')->with(['success' => 'User MO successfully saved']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response  php 
     */
    
    public function add_leader($id)
    {
        $leader = User::get();
        $detail = User::where('id', '=', $id)->first();

        return view('adminpage.user.mo.add_leader', compact('leader','detail'));

    }

    
    public function post_leader(Request $request)
    {
        $id = $request->input('id');

        $st = User::find($id);
        $st->leader = $request->input('leader');
        $st->name_leader = $request->input('name_mo');
        $st->save();

        return redirect('mo')->with(['update' => 'User MO successfully updated']);
    }

    public function updatestatus1($id)
    {
        $st = User::find($id);
        $st->status = '1';
        $st->save();

        return redirect('mo')->with(['update' => 'User MO successfully updated']);
    }

    public function updatestatus2($id)
    {
        $st = User::find($id);
        $st->status = '0';
        $st->save();

        return redirect('mo')->with(['update' => 'User MO successfully updated']);
    }

    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $mo = User::where('id',$id)->first();
        $roles = Role::where('id','=', '3')->pluck('name', 'id');

        return view('adminpage.user.mo.edit', compact('roles', 'mo'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    private function syncPermissions(Request $request, $user)
    {
        // Get the submitted roles
        $roles = $request->get('roles', []);
        $permissions = $request->get('permissions', []);

        // Get the roles
        $roles = Role::find($roles);

        // check for current role changes
        if( ! $user->hasAllRoles( $roles ) ) {
            // reset all direct permissions for user
            $user->permissions()->sync([]);
        } else {
            // handle permissions
            $user->syncPermissions($permissions);
        }

        $user->syncRoles($roles);

        return $user;
    }

    public function add_manager($id)
    {
        $manager = User::get();
        $detail = User::where('id', '=', $id)->first();

        $users          = User::get();        
        //$roless         = $users->model->role->id;

        $role  = Model_has_role::where('role_id', 5)->get();
        
        $mng = Manager::get(); 



        return view('adminpage.user.mo.add_manager', compact('manager','detail', 'mng'));
    }

    
    public function post_manager(Request $request)
    {
        $id = $request->input('id');
        $mg =  $request->input('manager');

        $st = User::find($id);
        $name = User::where('id',$mg)->limit(1)->first();

        $st->manager      = $request->input('manager');
        $st->name_manager = $name->name;
        $st->save();

        return redirect('mo')->with(['update' => 'User Manager successfully updated']);
    }
}

resources/views/adminpage/user/mo/add_leader.blade.php
@extends('vadmin.tampilan')

@section('content')

	<section class="content">
        <div class="container-fluid">

            <div class="row clearfix"> <!-- Breadcrumber -->
                <div class="col-md-6">
                    <ol class="breadcrumb breadcrumb-col-pink">
                        <li><a href="javascript:void(0);"><i class="material-icons">person</i> User</a></li>
                        <li class="active"><i class="material-icons">person_add</i>MO User</li>
                    </ol>
                </div>
            </div> <!-- End of breadcrumber -->

			<!-- Horizontal Layout -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header bg-red">
                            <h2>
                                Detail MO
                            </h2>
                        </div>

                        <div class="body">
                            <form class="form-horizontal" method="post" action="{{url('mo/add_leader')}}">

                            	<input type="text" name="id" value="{{$detail->id}}" hidden>

                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="email_address_2">ID</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="email_address_2" class="form-control" value="US{{$detail->id}}" disabled>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="password_2">Name</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="password_2" class="form-control" name="name" value="{{$detail->name}}" disabled>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="password_2">Email</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="password_2" class="form-control" value="{{$detail->email}}" disabled>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="password_2">Status</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                            	@if($detail->status == 1)
                                                <input type="text" id="password_2" class="form-control" value="Aktif" disabled>
                                                @else
                                                <input type="text" id="password_2" class="form-control" value="Tidak Aktif" disabled>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="password_2" class="bg-red">Leader</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <select class="form-control" name="leader">
                                                	@foreach($leader as $data)
                                                        @if($data->model->role->id == '12')
                                                	   <option value="{{$data->id}}">US{{$data->id}} - {{$data->name}}</option>
                                                        <input type="hidden" name="name_mo" value="{{$data->name}}" >
                                                        @endif
                                                	@endforeach

                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row clearfix">
                                	<div class="col-xs-6 col-sm-3 col-md-2 col-lg-2 col-md-offset-10">
                                        <button type="submit" class="btn bg-green btn-block btn-lg waves-effect">
                                            Save
                                        </button>
                                        {{ csrf_field() }}
                                    </div>
                                </div>
                                
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Horizontal Layout -->
        </div>
    </section>

@endsection

resources/views/adminpage/user/mo/index.blade.php
@extends('vadmin.tampilan')

@section('content')

	<section class="content">
        <div class="container-fluid">

            <div class="row clearfix"> <!-- Breadcrumber -->
                <div class="col-md-6">
                    <ol class="breadcrumb breadcrumb-col-pink">
                        <li><a href="javascript:void(0);"><i class="material-icons">person</i> User MO</a></li>
                        
                    </ol>
                </div>
            </div> <!-- End of breadcrumber -->

            <!-- Notification -->
            <div class="row clearfix">
                @if ($message = Session::get('success')) 
                <div class="alert bg-green alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ $message }}
                </div>
                @elseif($message = Session::get('delete'))
                <div class="alert bg-pink alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ $message }}
                </div>
                @elseif($message = Session::get('update'))
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ $message }}
                </div>
                @endif
            </div>
            <!-- End of Notif -->

            <div class="row clearfix demo-button-sizes">
                <div class="col-md-10"></div>
                @can('add_users')
                <div class="col-xs-6 col-sm-3 col-md-2 col-lg-2">
                    <a href="{{ route('mo.create') }}" type="submit" class="btn btn-success btn-block btn-lg waves-effect" style="cursor:pointer;">
                      Add
                    </a>
                </div>
                @endcan
            </div>

		    <div class="row clearfix">
                <div class="card">
                    <div class="header bg-red">
                        <h2>Data MO -- </h2>
                    </div>
                    <div class="body">
                        <table class="table" id="example">
                        	<thead>
                                <tr>
                                    <th>#</th>
                                    <th>ID</th>
					                <th>Name</th>
					                <th>Email</th>
					                <th>Leader</th>
                                    <th>Manager</th>
					                <th>Status</th>
					                <th class="text-center">Actions</th>          
                                </tr>
                            </thead>
                            <tbody>
                                <?php $i = 1; ?>

                            	@foreach($result as $item)
                                @if($item->model->role->id == 3)
				                <tr>
				                    <td>{{$i++}}</td>
                                    <td>US{{ $item->id }}</td>
				                    <td>{{ $item->name }}</td>
				                    <td>{{ $item->email }}</td>
				                    
				                    <td>
										
                                        @if(empty($item->leader) )
                                        <a href="{{url('/add_leader/'.$item->id)}}" class="btn btn-primary"><i class="material-icons disabled">person</i> Add Leader </a>
                                        @elseif(!empty($item->leader) )
                                            <span class="btn btn-danger">{{$item->name_leader}}</span>
                                        @else
                                            <span class="label bg-white">Follower</span>
                                        @endif
				                    </td>
                                    <td>

                                        @if(empty($item->manager))
                                        <a href="{{url('/add_manager/'.$item->id)}}" class="btn btn-primary"><i class="material-icons disabled">person</i> Add Manager </a>
                                        @else
                                            <span class="btn btn-danger">{{$item->name_manager}}</span>
                                        @endif
                                    </td>
				                    <td>
                                        <div class="switch">  <!-- update status ini belum -->
                                            @if($item->status == 0)
                                            <label>Non Act<a href="{{url('/mo/update1/'.$item->id)}}" class="lever switch-col-red" onclick="alert('User MO akan di aktif!');"></a>Active</label>
                                            @else
                                            <label>Non Act<a href="{{url('/mo/update2/'.$item->id)}}" onclick="alert('User MO akan di nonaktif!');">
                                                <input type="checkbox" id="aksi" name="status" checked><span class="lever switch-col-red"></span></a>Active</label>
                                            @endif
                                        </div>
	                            	</td>

				                    @can('edit_users')
				                    <td class="text-center">
				                        @include('shared._actions', [
				                            'entity' => 'mo',
				                            'id' => $item->id
				                        ])
				                    </td>
				                    @endcan
				                </tr>
                                @endif
				            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

		    
        </div>
    </section>
    

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>

    <script>
        $(document).ready(function() {
        $('#example').DataTable();
        });
    </script>

    <!-- <script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script> -->

    <!-- jquery for status -->

    <script type="text/javascript">
        
    </script>
    <!-- End status -->

@endsection

resources/views/adminpage/user/mo/new.blade.php
@extends('vadmin.tampilan')

@section('content')

	<section class="content">
        <div class="container-fluid">

            <div class="row clearfix"> <!-- Breadcrumber -->
                <div class="col-md-6">
                    <ol class="breadcrumb breadcrumb-col-pink">
                        <li><a href="{{route('mo.index')}}"><i class="material-icons">person</i> User MO</a></li>
                        <li class="active"><i class="material-icons">person_add</i>MO User</li>
                    </ol>
                </div>
            </div> <!-- End of breadcrumber -->

		    <div class="row clearfix">
		        <div class="col-lg-12">
		        	<div class="card">
		        		<div class="header bg-red">Add</div>
		        		<div class="body">
				            {!! Form::open(['route' => ['mo.store'] ]) !!}
				            	@include('adminpage.user.mo.form')
				                
				                <!-- Submit Form Button -->
				                <div class="row clearfix">
                                	<div class="col-xs-6 col-sm-3 col-md-2 col-lg-2 col-md-offset-10">
                                        <button type="submit" class="btn bg-green btn-block btn-lg waves-effect">
                                            Save
                                        </button>
                                        {{ csrf_field() }}
                                    </div>
                                </div>
				            {!! Form::close() !!}
			            </div>
		            </div>
		        </div>
		    </div>
        </div>
    </section>

@endsection